#!/bin/sh
# to do all this in nodejs is annoying, may as well do it in a seperate process
cd "$(dirname "$0")" || exit $?
../codec/cdecoder "$1" /dev/stdout 2>/dev/null | \
    ../codec/sdecoder /dev/stdin /dev/stdout 2>/dev/null | \
    ffmpeg -f s16le -ar 8000 -i - -f mp3 "$1.mp3" 1>/dev/null 2>/dev/null
mv "$1.mp3" "$2"
rm "$1"